# Generated by cucumber-sinatra. (2013-11-14 11:28:06 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/supercraic.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = WhatCraic

class WhatCraicWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  WhatCraicWorld.new
end
